### PR TITLE
milestone/frontend

### PR DESCRIPTION
**Pull request by ellmau**
# What does this PR do?

* Provide a graphical frontend for the solver

Related to #76 

# Checklist before creating a non-draft PR

- [x] All tests are passing
- [x] Clippy has no complains
- [x] Code is `rustfmt` formatted
- [x] Applicable labels are chosen (Note: it is not necessary to replicate the labels from the related issues)
- [x] There are no other open [Pull Requests](https://github.com/ellmau/adf-obdd/pulls) for the same update/change.
  - [ ] If there is a good reason to have another PR for the same update/change, it is well justified.

# Checklist on Guidelines and Conventions

- [x] Commit messages follow our guidelines
- [x] Code is self-reviewed
- [x] Naming conventions are met
- [x] New features are tested
  - [ ] `quickcheck` has been considered
  - [ ] All variants are considered and checked
- Clippy Compiler-exceptions
  - [x] Used in a sparse manner
  - [ ] If used, a separate comment describes and justifies its use
- [x] `rustdoc` comments are self-reviewed and descriptive
- Error handling
  - [ ] Use of `panic!(...)` applications is justified on non-recoverable situations
  - [ ] `expect(...)` is used over `unwrap()` (except obvious test-cases)
- [x] No unsafe code (exceptions need to be discussed specifically)

### CODE REVIEW

**Comment by ellmau** [comment]
path and version in Cargo.toml allows to use path in normal builds and the crates.io version when packaging

**Comment by ellmau** [comment]
FYI: The `./assets` folder is not part of the repository.

**Comment by monsterkrampe** [comment]
> FYI: The `./assets` folder is not part of the repository.

This is currently intended, do not want to include the compiled frontend assets in the repo.
The `Dockerfile` illustrates a possible way of bringing frontend assets and the server together.
Still, I need to think of a way to setup a proper (local) buildchain for this...

**Comment by monsterkrampe** [comment]
Btw the `Dockerfile` can also be used for testing:

Build the image (this will take quite a while):
```
docker build -t adf-bdd-server .
```

Run server in container and bind to `localhost:80`:
```
docker run -p 80:8080 adf-bdd-server 
```

**Pull request merged**
